granSugar = float(input("Convert cups of granulated sugar into grams:"))
print(granSugar * 200)
cupOil = float(input("Convert cups of oil into grams:"))
print(cupOil * 225)
teaSalt = float(input("Convert teaspoon of salt into grams:"))
print(teaSalt * 6)
cupMilk = float(input("Convert cups of milk into grams:"))
print(cupMilk * 236)
teaBakSoda = float(input("Convert teaspoon of baking soda into grams:"))
print(teaBakSoda * 6)
apFlour = float(input("Convert cups of all purpose flour into grams:"))
print(apFlour * 120)
