# Name Of The Reciple
recipeTitle = "Challah"
# Converts Cups To Grams
apFlour = (0 * 120)
granSugar = (0 * 200)
powSugar = (0 * 130)
broSugar = (0 * 200)
breFlour = (5 * 200)
cakFlour = (0 * 120)
cocoaPowder = (0 * 100)
sourCream = (0 * 242)
cupButter = (.33 * 227)
water = (1 * 236)
milk = (0 * 240)
# Converts Teaspoon To Grams
salt = (2 * 6)
bakSoda = (0 * 6)
bakPowder = (0 * 4)
dryYeast = (4 * 3.5)
vanExtract = (0 * 4)
# Converts Tablespoon To Grams
butter = (0 * 14)
cream = (0 * 14)
tbspSugar = (2 * 12.5)
honey = (1 * 21)
# Individually In Grams
wholeEggs = (3 * 50)
eggWhites = (1 * 30)
eggYolks = (1 * 20)

print(recipeTitle)
print("All Purpose Flour: " + str(apFlour) + "g")
print("Granulated Sugar: " + str(granSugar) + "g")
print("Powdered Sugar: " + str(powSugar) + "g")
print("Brown Sugar: " + str(broSugar) + "g")
print("Bread Flour: " + str(breFlour) + "g")
print("Cake Flour: " + str(cakFlour) + "g")
print("Cocoa Powder: " + str(cocoaPowder) + "g")
print("Sour Cream: " + str(sourCream) + "g")
print("Cup Of Butter: " + str(cupButter) + "g")
print("Water: " + str(water) + "g")
print("Milk: " + str(milk) + "g")
print("Salt: " + str(salt) + "g")
print("Baking Soda: " + str(bakSoda) + "g")
print("Baking Powder: " + str(bakPowder) + "g")
print("Active Dry Yeast: " + str(dryYeast) + "g")
print("Vanilla Extract: " + str(vanExtract) + "g")
print("Butter: " + str(butter) + "g")
print("Heavy Whipping Cream: " + str(cream) + "g")
print("Table Spoon Sugar: " + str(tbspSugar) + "g")
print("Honey: " + str(honey) + "g")
print("Whole Eggs: " + str(wholeEggs) + "g")
print("Egg White: " + str(eggWhites) + "g")
print("Egg Yolks: " + str(eggYolks) + "g")
