# Name Of The Reciple
# recipeTitle = ""
# Converts Cups To Gram
# granSugar = (1 * 200)
# powSugar = (0 * 130)
# broSugar = (0 * 200)
# apFlour = (1 * 120)
# breFlour = (0 * 200)
# cakFlour = (0 * 120)
# cocoaPowder = (.5 * 100)
# sourCream = (1 * 242)
# cupButter = (1 * 227)
# cupWater = (0 * 236)
# cupMilk = (0 * 240)
# Converts Teaspoon To Grams
# salt = (0 * 6)
# bakSoda = (0 * 6)
# bakPowder = (0 * 4)
# dryYeast = (0 * 3.5)
# vanExtract = (0 * 4)
# Converts Tablespoon To Grams
# tbspButter = (0 * 14)
# cream = (0 * 14)
# tbspSugar = (0 * 12.5)
# honey = (0 * 21)
# tbspOil = (0 * 13)
# Individually In Grams
# wholeEggs = (0 * 50)
# eggWhites = (0 * 30)
# eggYolks = (0 * 20)

# Converting inputs of ingredients from cups to grams
granSugar = float(input("Convert cups of granulated sugar into grams:"))
print(granSugar * 200)
powSugar = float(input("Convert cups of powdered sugar into grams:"))
print(powSugar * 130)
broSugar = float(input("Convert cups of brown sugar into grams:"))
print(broSugar * 200)
apFlour = float(input("Convert cups of all purpose flour into grams:"))
print(apFlour * 120)
breFlour = float(input("Convert cups of bread flour into grams:"))
print(breFlour * 220)
cakFlour = float(input("Convert cups of cake flour into grams:"))
print(cakFlour * 120)
cocoaPowder = float(input("Convert cups of cocoa powder into grams:"))
print(cocoaPowder * 100)
sourCream = float(input("Convert cups of sour cream into grams:"))
print(sourCream * 242)
cupButter = float(input("Convert cups of butter into grams:"))
print(cupButter * 227)
cupWater = float(input("Convert cups of water into grams:"))
print(cupWater * 236)
cupMilk = float(input("Convert cups of milk into grams:"))
print(cupMilk * 236)
cupOil = float(input("Convert cups of oil into grams:"))
print(cupOil * 225)
# Converting inputs of ingredients from Teaspoons to grams
teaSalt = float(input("Convert teaspoon of salt into grams:"))
print(teaSalt * 6)
teaBakSoda = float(input("Convert teaspoon of baking soda into grams:"))
print(teaBakSoda * 6)
teaBakPowder = float(input("Convert teaspoon of baking powder into grams:"))
print(teaBakPowder * 4)
dryYeast = float(input("Convert teaspoon of yeast into grams:"))
print(dryYeast * 3.5)
vanExtract = float(input("Convert teaspoon of vanilla extract into grams:"))
print(vanExtract * 4)
# Converting inputs of ingredients from Tablespoons to grams
tbspButter = float(input("Convert tablespoon of butter into grams:"))
print(tbspButter * 14)
tbspCream = float(input("Convert tablespoon of heavy cream into grams:"))
print(tbspCream * 14)
tbspSugar = float(input("Convert tablespoon of granulated sugar into grams:"))
print(tbspSugar * 12.5)
tbspHoney = float(input("Convert tablespoon of honey into grams:"))
print(tbspHoney * 21)
tbspOil = float(input("Convert tablespoon of oil into grams:"))
print(tbspOil * 13)
# Converting inputs of ingredients each into grams
wholeEggs = float(input("Convert one whole egg into grams:"))
print(wholeEggs * 50)
eggWhites = float(input("Convert one egg white into grams:"))
print(eggWhites * 30)
eggYolks = float(input("Convert one egg yolk into grams:"))
print(eggYolks * 20)

# print(recipeTitle)
# print("Granulated Sugar: " + str(granSugar) + "g")
# print("Powdered Sugar: " + str(powSugar) + "g")
# print("Brown Sugar: " + str(broSugar) + "g")
# print("All Purpose Flour: " + str(apFlour) + "g")
# print("Bread Flour: " + str(breFlour) + "g")
# print("Cake Flour: " + str(cakFlour) + "g")
# print("Cocoa Powder: " + str(cocoaPowder) + "g")
# print("Sour Cream: " + str(sourCream) + "g")
# print("Butter(cup conversion): " + str(cupButter) + "g")
# print("Water: " + str(cupWater) + "g")
# print("Milk: " + str(cupMilk) + "g")
# print("Salt: " + str(salt) + "g")
# print("Baking Soda: " + str(bakSoda) + "g")
# print("Baking Powder: " + str(bakPowder) + "g")
# print("Active Dry Yeast: " + str(dryYeast) + "g")
# print("Vanilla Extract: " + str(vanExtract) + "g")
# print("Oil: " + str(tbspOil) + "g")
# print("Butter(tablespoon conversion): " + str(tbspButter) + "g")
# print("Heavy Whipping Cream: " + str(cream) + "g")
# print("Sugar(tablespoon conversion): " + str(tbspSugar) + "g")
# print("Honey: " + str(honey) + "g")
# print("Whole Eggs: " + str(wholeEggs) + "g")
# print("Egg White: " + str(eggWhites) + "g")
# print("Egg Yolks: " + str(eggYolks) + "g")
