# Name Of The Reciple
recipeTitle = ""
# Converts Cups To Gram
granSugar = (0 * 200)
powSugar = (0 * 130)
broSugar = (0 * 200)
apFlour = (0 * 120)
breFlour = (0 * 200)
cakFlour = (0 * 120)
cocoaPowder = (0 * 100)
sourCream = (0 * 242)
cupButter = (0 * 227)
cupWater = (0 * 236)
cupMilk = (0 * 240)
# Converts Teaspoon To Grams
salt = (0 * 6)
bakSoda = (0 * 6)
bakPowder = (0 * 4)
dryYeast = (0 * 3.5)
vanExtract = (0 * 4)
# Converts Tablespoon To Grams
tbspButter = (0 * 14)
cream = (0 * 14)
tbspSugar = (0 * 12.5)
honey = (0 * 21)
tbspOil = (0 * 13)
# Individually In Grams
wholeEggs = (0 * 50)
eggWhites = (0 * 30)
eggYolks = (0 * 20)

print(recipeTitle)
print("Granulated Sugar: " + str(granSugar) + "g")
print("Powdered Sugar: " + str(powSugar) + "g")
print("Brown Sugar: " + str(broSugar) + "g")
print("All Purpose Flour: " + str(apFlour) + "g")
print("Bread Flour: " + str(breFlour) + "g")
print("Cake Flour: " + str(cakFlour) + "g")
print("Cocoa Powder: " + str(cocoaPowder) + "g")
print("Sour Cream: " + str(sourCream) + "g")
print("Butter(cup conversion): " + str(cupButter) + "g")
print("Water: " + str(cupWater) + "g")
print("Milk: " + str(cupMilk) + "g")
print("Salt: " + str(salt) + "g")
print("Baking Soda: " + str(bakSoda) + "g")
print("Baking Powder: " + str(bakPowder) + "g")
print("Active Dry Yeast: " + str(dryYeast) + "g")
print("Vanilla Extract: " + str(vanExtract) + "g")
print("Oil: " + str(tbspOil) + "g")
print("Butter(tablespoon conversion): " + str(tbspButter) + "g")
print("Heavy Whipping Cream: " + str(cream) + "g")
print("Sugar(tablespoon conversion): " + str(tbspSugar) + "g")
print("Honey: " + str(honey) + "g")
print("Whole Eggs: " + str(wholeEggs) + "g")
print("Egg White: " + str(eggWhites) + "g")
print("Egg Yolks: " + str(eggYolks) + "g")
