apFlour = float(input("Convert cups of all purpose flour into grams:"))
print(apFlour * 120)
cupOil = float(input("Convert cups of oil into grams:"))
print(cupOil * 225)
cupWater = float(input("Convert cups of water into grams:"))
print(cupWater * 236)
teaSalt = float(input("Convert teaspoon of salt into grams:"))
print(teaSalt * 6)
teaBakPowder = float(input("Convert teaspoon of baking powder into grams:"))
print(teaBakPowder * 4)
